const ITEMS=[
{icon:'🎫',label:'БИЛЕТ',kind:'good',points:20},{icon:'✅',label:'ПЕЧАТЬ',kind:'good',points:30},{icon:'📄',label:'ПРИКАЗ',kind:'good',points:15},{icon:'☕',label:'КОФЕ',kind:'shield',points:5},
{icon:'🚕',label:'ПРОБКА',kind:'bad'},{icon:'🧱',label:'ПРАВКИ',kind:'bad'},{icon:'❌',label:'ОТМЕНА',kind:'bad'},{icon:'🧳',label:'БАГАЖ?',kind:'bad'}];
const $=id=>document.getElementById(id);let lane=0,score=0,hp=3,left=35,running=false,shield=false,spawnId,tickId,startAt,objects=[],lastTouch=0;
function screen(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('show'));$(id).classList.add('show')}
function move(d){if(!running)return;lane=Math.max(0,Math.min(2,lane+d));$('player').style.left=`${(lane+.5)*33.333}%`}
function start(){objects.forEach(o=>o.el.remove());objects=[];lane=0;score=0;hp=3;left=35;shield=false;running=true;startAt=Date.now();$('player').style.left='16.666%';$('player').classList.remove('shield');update();screen('game');spawnId=setInterval(spawn,620);tickId=setInterval(loop,30)}
function spawn(){if(!running)return;const data=ITEMS[Math.floor(Math.random()*ITEMS.length)],l=Math.floor(Math.random()*3),el=document.createElement('div');el.className='object';el.style.left=`${(l+.5)*33.333}%`;el.innerHTML=`${data.icon}<small>${data.label}</small>`;$('road').appendChild(el);objects.push({el,data,lane:l,y:18,speed:1.15+Math.random()*.55,hit:false})}
function loop(){const elapsed=(Date.now()-startAt)/1000;left=Math.max(0,Math.ceil(35-elapsed));objects.forEach(o=>{o.y+=o.speed;o.el.style.top=o.y+'%';if(!o.hit&&o.y>78&&o.y<94&&o.lane===lane){o.hit=true;collect(o)}if(o.y>105)o.el.remove()});objects=objects.filter(o=>o.y<=105);update();if(left<=0||hp<=0)finish()}
function collect(o){o.el.remove();o.y=999;if(o.data.kind==='good'){score+=o.data.points;toast(`+${o.data.points} ${o.data.label}`,'#4ade80')}else if(o.data.kind==='shield'){score+=5;shield=true;$('player').classList.add('shield');toast('☕ КОФЕ-ЩИТ!','#67e8f9')}else if(shield){shield=false;$('player').classList.remove('shield');toast('ЩИТ СПАС ОТ ПРАВОК','#67e8f9')}else{hp--;score=Math.max(0,score-10);navigator.vibrate?.(80);toast(`-${10} ${o.data.label}`,'#fb7185')}}
function toast(t,c){$('toast').textContent=t;$('toast').style.color=c;clearTimeout(toast.id);toast.id=setTimeout(()=>$('toast').textContent='',650)}
function update(){$('score').textContent=score;$('hp').textContent=hp;$('time').textContent=left}
function finish(){if(!running)return;running=false;clearInterval(spawnId);clearInterval(tickId);const elapsed=Math.round((Date.now()-startAt)/1000),passed=score>=140&&hp>0,medal=score>=260?'🥇':score>=200?'🥈':passed?'🥉':'-';$('resultEmoji').textContent=passed?'✈️🏁':'🧳💥';$('resultTitle').textContent=passed?'РЕЙС СОГЛАСОВАН!':'КОМАНДИРОВКА СОРВАНА';$('resultText').textContent=passed?'Ты успел на рейс, сохранил документы и почти не помял костюм.':'Набери 140 очков и сохрани хотя бы одно сердце.';$('stats').textContent=`${score} очков · ${hp} ❤️ · ${elapsed} сек.`;if(passed)Progress.completeLevel(5,{time:elapsed,score,medal});else Progress.sendAnalytics(5,{time:elapsed,distance:score,medal,result:'fail'});screen('result');loadLeaderboard()}
function loadLeaderboard(){Progress.fetchLeaderboard(5,list=>{const el=$('lb5');if(!list.length){el.innerHTML='<div class="lb-empty">Табло вылетов пусто</div>';return}const m=['🥇','🥈','🥉','👍','👍'];el.innerHTML=list.map((e,i)=>`<div class="lb-row"><span class="lb-rank">${m[i]}</span><span class="lb-name">${Progress.escapeHtml(e.name)}</span><span class="lb-score">${e.score}</span></div>`).join('')})}
$('startBtn').onclick=start;$('retry').onclick=start;$('left').onclick=()=>move(-1);$('right').onclick=()=>move(1);document.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')move(-1);if(e.key==='ArrowRight')move(1)});$('road').addEventListener('touchstart',e=>lastTouch=e.touches[0].clientX,{passive:true});$('road').addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-lastTouch;if(Math.abs(dx)>25)move(dx>0?1:-1)},{passive:true});Telegram?.WebApp?.expand?.();Telegram?.WebApp?.disableVerticalSwipes?.();
